### ISSUE TITLE
网络不给力

### ISSUE THREAD

**Issue by jksfood** [8tory/weibo-android-sdk#10]
我需要的是微博登录，将您的demo中微博登录的部分单独拿了出来，可是运行时为什么总是报网络错误（C401）？？？您的demo里的登录就没问题，您能告诉我是为什么吗、?

**Comment by yongjhih** [comment]
https://github.com/sinaweibosdk/weibo_android_sdk/issues/142

**Comment by yongjhih** [comment]
https://github.com/sinaweibosdk/weibo_android_sdk/issues/144

**Comment by yongjhih** [comment]
試試使用各種版本 3.1.4, 3.1.2, 3.1.1 。

``` gradle
    compile 'com.infstory:weibo-android-sdk:3.1.4'
```

or

``` gradle
    compile 'com.infstory:weibo-android-sdk:3.1.2'
```

or

``` gradle
    compile 'com.infstory:weibo-android-sdk:3.1.1'
```

這裡提供 android studio 方便匯入，但尚未與官方版本無太大差異，故建議集中前往官方討論。

另外也可參考： https://github.com/8tory/SimpleWeibo

**Comment by yongjhih** [comment]
這是整理關於認證部份的源碼區段可參考：

![screenshot from 2016-05-04 20 04 45-2](https://cloud.githubusercontent.com/assets/213736/15013875/cf15c162-1234-11e6-81b2-51e623dbaf10.png)

``` java
final String appKey = "2045436852"; // 這裡請修改成你自己申請到的 App Key
final String redirectUrl = "https://api.weibo.com/oauth2/default.html"; // 與上圖官網後台設定一致
final String scope = "";

mSsoHandler = new SsoHandler(mActivity, new AuthInfo(mActivity, appKey, redirectUrl, scope));
mSsoHandler.authorize(new WeiboAuthListener {
    @Override
    public void onComplete(Bundle values) {
        Oauth2AccessToken token = Oauth2AccessToken.parseAccessToken(values);
        if (token.isSessionValid()) {
            getPreferences(MODE_PRIVATE).edit()
                  .putString("uid", token.getUid())
                  .putString("access_token", token.getToken())
                  .putString("refresh_token", token.getRefreshToken())
                  .putString("expires_in", token.getExpiresTime())
                  .commit();
        }
    }

    @Override
    public void onCancel() {
    }

    @Override
    public void onWeiboException(WeiboException e) {
        e.printStackTrace();
    }
});
```

**Comment by yongjhih** [comment]
ref. https://github.com/sinaweibosdk/weibo_android_sdk/blob/master/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%20FAQ.md#5-关于授权

**Comment by jksfood** [comment]
不好意思  这么久才回复你，我的意思是，我将你的工程中的weibo-android-sdk单独提取出来，然后将你的AccessTokenKeeper、Constants、WBAuthActivity、WBAuthCodeActivity单独放在一个包中，在mainfest加入了如下代码：

``` xml
<activity android:name=".login.sina.WBAuthCodeActivity" />
        <activity android:name=".login.sina.WBAuthActivity" />
        <!-- 必须注册在微博授权，分享微博时候用到 -->
        <activity android:name="com.sina.weibo.sdk.component.WeiboSdkBrowser"
            android:configChanges="keyboardHidden|orientation"
            android:windowSoftInputMode="adjustResize"
            android:exported="false" >
        </activity>
        <meta-data
            android:name="WEIBO_APPKEY"
            android:value="2045436852" />
        <meta-data
            android:name="WEIBO_CHANNEL"
            android:value="weibo" />
```

可是 为什么一提示下面的信息：“网络不给力，请 稍后再试吧（C401）”，我想知道我哪里还缺什么吗？

**Comment by jksfood** [comment]
当然  权限我也加了的
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by jksfood** [comment]
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by jksfood** [comment]
当然  权限我也加了的
aa<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />aa

**Comment by jksfood** [comment]
是不是跟keystore有关系？我们工程的包名不一样

**Comment by yongjhih** [comment]
包名與 keystore 設定方法在官方手冊中已經有說明 (例如：集成前准备章節)

**Comment by jksfood** [comment]
官方文档比较晦涩，尤其是android studio这块，并且并没有讲清楚如何在自己项目中运用，讲的是demo方面的，我demo没问题，我想知道的是我现在究竟该怎么做，才能授权成功，官方文档我已经看了两天了，原谅我没看懂

**Comment by yongjhih** [comment]
集成的部份，事實上與 Android Studio 無關的。

這裡附上大概的集成步驟，將 weibo-android-sdk-demo 改成自己的微博應用，來練習驗證集成：

``` sh
$ git clone https://github.com/8tory/weibo-android-sdk/
$ cd weibo-android-sdk/
```

修改 `MODIFY` 標注的地方 (e.g. 對應的 "包名", "App Key", "回調網址")
- [weibo-android-sdk-demo/src/main/AndroidManifest.xml](https://github.com/8tory/weibo-android-sdk/blob/master/weibo-android-sdk-demo/src/main/AndroidManifest.xml)
- [weibo-android-sdk-demo/src/main/java/com/sina/weibo/sdk/demo/Constants.java](https://github.com/8tory/weibo-android-sdk/blob/master/weibo-android-sdk-demo/src/main/java/com/sina/weibo/sdk/demo/Constants.java)

編譯 apk 並安裝 (這裡舉例透過 `gradlew` 指令。也可以是透過 eclipse 或者 android studio 編譯)

``` sh
$ ./gradlew assemble
$ adb install -r ./weibo-android-sdk-demo/build/outputs/apk/weibo-android-sdk-demo-debug.apk
```

安裝 [微博採集 App 簽名.apk](https://github.com/sinaweibosdk/weibo_android_sdk/raw/master/app_signatures.apk) ，採集 App 簽名

``` sh
$ adb install -r app_signatures.apk
```

進入微博開發平台，設定對應的 "包名", "簽名" 以及 "回調網址"

## 進階 (選用 Optional)

為了提昇安全性，應該使用自己的 keystore (私密鑰匙/神秘墨水) 來為你的 App 署名，製作自己的 keystore (ref. http://developer.android.com/tools/publishing/app-signing.html#signing-manually):

``` sh
$ keytool -genkey -v -keystore my-release-key.keystore
-alias alias_name -keyalg RSA -keysize 2048 -validity 10000
```

**Comment by jksfood** [comment]
好的吧，谢谢了
