### ISSUE TITLE
Share to weibo in Fragments

### ISSUE THREAD

**Issue by AllenVork** [8tory/weibo-android-sdk#6]
I have a DialogFragment in an Activity, and i share things to weibo in this Fragment. When sharing success to weibo, it navigates back to my app.But it doesn't invoke onNewIntent, just invoke onActivityResult and the intent is null.I don't know why.

**Comment by yongjhih** [comment]
You should report into official project: https://github.com/sinaweibosdk/weibo_android_sdk/issues . This project is unofficial gradlized project for sinaweibosdk/weibo_android_sdk .

**Comment by yongjhih** [comment]
BTW, Could you write a test case to highlight it?
