### ISSUE TITLE
想问一下作者这个可以直接在AS上用吗？

### ISSUE THREAD

**Issue by Creep0824** [8tory/weibo-android-sdk#7]

**Comment by yongjhih** [comment]
可以阿，基本上這就是 gradle 化的專案，所以可以拿給 AS 使用。

兩種引用方法，一種是 clone 下來，當作源碼 module。另一種是預編譯版本，透過網路引用:

``` gradle
dependencies {
    compile 'com.infstory:weibo-android-sdk:3.1.2'
}
```

**Comment by yongjhih** [comment]
另外，推薦 https://github.com/8tory/SimpleWeibo 專案，重新包裝了 Weibo API ，且擴充 API 很容易，歡迎 PR。

**Comment by Creep0824** [comment]
这个和原版SDK的使用有区别吗？小白求教，谢谢啦😊 Sent from Mail Master 在2016年04月12日 22:23 ，Andrew Chen写道： 可以阿，基本上這就是 gradle 化的專案，所以可以拿給 AS 使用。 兩種引用方法，一種是 clone 下來，當作源碼 module，另一種是透過網路引用: dependencies {
    compile 'com.infstory:weibo-android-sdk:3.1.2'
} — You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub

**Comment by yongjhih** [comment]
8tory/weibo-android-sdk 與 sinaweibosdk/weibo_android_sdk 就實際內容，基本上沒有差別，純粹 gradle 化專案。

專案說明文件裡面已經有說明差異：

https://github.com/8tory/weibo-android-sdk#what-is-difference-between-sinaweibosdkweibo_android_sdk-and-8toryweibo-android-sdk
